apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-publish-nan
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-publish-nan
  template:
    metadata:
      labels:
        name: nginx-publish-nan
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - master
      imagePullSecrets:
        - name: regcred
      containers:
        - name: nginx
          image: registry.cn-shanghai.aliyuncs.com/fuck-study/soybean-admin:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-publish-nan
spec:
  selector:
    name: nginx-publish-nan
  ports:
    - protocol: TCP
      port: 80
  type: ClusterIP
