apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-publish-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-publish
  template:
    metadata:
      labels:
        name: nginx-publish
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - master
      imagePullSecrets:
        - name: regcred
      containers:
        - name: nginx
          image: registry.cn-shanghai.aliyuncs.com/fuck-study/nginx-publish:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-publish
spec:
  selector:
    name: nginx-publish
  ports:
    - protocol: TCP
      port: 80
  type: ClusterIP  # 根据需要选择Service类型
