/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  file: () => import("@/views/file/index.vue"),
  function_file: () => import("@/views/function/file/index.vue"),
  function_order: () => import("@/views/function/order/index.vue"),
  function_submit: () => import("@/views/function/submit/index.vue"),
  home: () => import("@/views/home/index.vue"),
  log: () => import("@/views/log/index.vue"),
  "plat-center": () => import("@/views/plat-center/index.vue"),
  plat: () => import("@/views/plat/index.vue"),
  report: () => import("@/views/report/index.vue"),
  tiku: () => import("@/views/tiku/index.vue"),
  "user-center": () => import("@/views/user-center/index.vue"),
  user_list: () => import("@/views/user/list/index.vue"),
  user_template: () => import("@/views/user/template/index.vue"),
};
