/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true
    }
  },
  {
    name: 'function',
    path: '/function',
    component: 'layout.base',
    meta: {
      title: 'function',
      i18nKey: 'route.function',
      icon: 'icon-park-outline:all-application',
      order: 6
    },
    children: [
      {
        name: 'function_order',
        path: '/function/order',
        component: 'view.function_order',
        meta: {
          icon: 'ant-design:ordered-list-outlined',
          title: 'function_order',
          i18nKey: 'route.function_order',
          order: 7
        }
      },
      {
        name: 'function_submit',
        path: '/function/submit',
        component: 'view.function_submit',
        meta: {
          icon: 'ant-design:search-outlined',
          title: 'function_submit',
          i18nKey: 'route.function_submit',
          order: 5
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'log',
    path: '/log',
    component: 'layout.base$view.log',
    meta: {
      icon: 'ant-design:file-text-outlined',
      title: 'log',
      i18nKey: 'route.log',
      order: 13
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true
    }
  },
  {
    name: 'plat-center',
    path: '/plat-center',
    component: 'layout.base$view.plat-center',
    meta: {
      title: 'plat-center',
      i18nKey: 'route.plat-center',
      icon: 'ant-design:api-outlined',
      order: 14
    }
  },
  {
    name: 'report',
    path: '/report',
    component: 'layout.base$view.report',
    meta: {
      icon: 'ant-design:message-outlined',
      title: 'report',
      i18nKey: 'route.report',
      order: 16
    }
  },
  {
    name: 'user',
    path: '/user',
    component: 'layout.base',
    meta: {
      icon: 'ant-design:team-outlined',
      roles: ['R_ADMIN'],
      title: 'user',
      i18nKey: 'route.user',
      order: 12
    },
    children: [
      {
        name: 'user_list',
        path: '/user/list',
        component: 'view.user_list',
        meta: {
          icon: 'ant-design:usergroup-add-outlined',
          title: 'user_list',
          i18nKey: 'route.user_list'
        }
      },
      {
        name: 'user_template',
        path: '/user/template',
        component: 'view.user_template',
        meta: {
          icon: 'ant-design:profile-outlined',
          title: 'user_template',
          i18nKey: 'route.user_template'
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      icon: 'ant-design:user-outlined',
      title: 'user-center',
      i18nKey: 'route.user-center',
      order: 13
    }
  }
];
